server.port=8091

key=AIzaSyC2yvDSeyNEGlSFgRnyc_Q9ybJC6iZHpJA
maxDistance=300
maxDistanceMatrixDistance=300
cacheEnabled=false

spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=proxyCache