spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.database=publikProxyCache
spring.threads.virtual.enabled=true
spring.data.mongodb.uri=${MONGO_URL:mongodb://localhost:27017/}
server.port=8090
google.api.key=${GOOGLE_APIKEY:AIzaSyC2yvDSeyNEGlSFgRnyc_Q9ybJC6iZHpJA}
cache.distance-matrix.min-distance=300
cache.directions.min-distance=300
cache.distance-matrix.timeout=30
googleApiCache=true
