
#key=AIzaSyC2yvDSeyNEGlSFgRnyc_Q9ybJC6iZHpJA
cacheEnabled=false

spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=proxyCache
server.port=8090
google.api.key=AIzaSyAHVFlX0bnarFsf6YvyzyRDwlyR6yHjZgQ
cache.distance-matrix.min-distance=300
cache.directions.min-distance=300
cache.distance-matrix.timeout=30
googleApiCache=true
